In [1]:
import torch
import os
from pathlib import Path
import pandas as pd
import numpy as np

In [30]:
path = Path("/local/scratch/a/shared/datasets/office_home_v1.0/")
metadata_array = []
OfficeHome_DOMAINS = ['Art', 'Clipart', 'Product', 'Real World']
OfficeHome_CATEGORIES=['Alarm_Clock', 'Backpack', 'Batteries', 'Bed', 'Bike', 'Bottle', 'Bucket', 'Calculator', 'Calendar', 'Candles', 'Chair', 'Clipboards', 'Computer', 'Couch', 'Curtains', 'Desk_Lamp', 'Drill', 'Eraser','Exit_Sign', 'Fan', 'File_Cabinet', 'Flipflops', 'Flowers', 'Folder', 'Fork', 'Glasses', 'Hammer', 'Helmet', 'Kettle', 'Keyboard', 'Knives', 'Lamp_Shade', 'Laptop', 'Marker', 'Monitor', 'Mop', 'Mouse', 'Mug', 'Notebook', 'Oven', 'Pan', 'Paper_Clip', 'Pen', 'Pencil', 'Postit_Notes', 'Printer', 'Push_Pin', 'Radio', 'Refrigerator', 'Ruler', 'Scissors', 'Screwdriver', 'Shelf', 'Sink', 'Sneakers', 'Soda', 'Speaker', 'Spoon', 'Table', 'Telephone', 'ToothBrush', 'Toys', 'Trash_Can', 'TV', 'Webcam']
index = 0
for x in path.iterdir():
    if x.is_dir():
        domain = x.name
        domain_remapped = OfficeHome_DOMAINS.index(domain)
        if domain == 'Art':
            split = 'test'
        elif domain == 'Real World':
            split = 'val'
        else:
            split = 'train'
        for fp in x.iterdir():
            category = fp.name
            y = OfficeHome_CATEGORIES.index(category)
            for im in fp.iterdir():
                image_path = im.relative_to(path)
                metadata_array.append([split, domain_remapped, domain, category, y, str(image_path)])
metadata_np = np.array(metadata_array)
rng = np.random.default_rng()
for dm in ['Clipart', 'Product']:
    for i in range(len(OfficeHome_CATEGORIES)):
        print(i)
        idx = np.logical_and(np.logical_and(metadata_np[:,0]=='train', metadata_np[:,2]==dm), metadata_np[:,4]==str(i)).nonzero()
        val_test = rng.choice(idx[0], np.floor(0.1*len(idx[0])).astype('int'))
        val = val_test[0:len(val_test)//2]
        test = val_test[len(val_test)//2:]
        print(val, test)
        print(len(val_test), len(val_test))
        metadata_np[val, 0] = 'id_val'
        metadata_np[test, 0] = 'id_test'
print(metadata_np)
print(np.unique(metadata_np[:,0]))
pd.DataFrame(metadata_np).to_csv("metadata.csv", index_label=("split", "domain_remapped" "domain", "category", 'y', "path"))


0
[2483 2433 2460] [2452 2450 2476]
6 6
1
[2528 2523] [2526 2500 2526]
5 5
2
[2560 2560 2585] [2605 2573 2561]
6 6
3
[2611 2686 2620 2621] [2696 2691 2694 2629 2689]
9 9
4
[2725 2706 2740 2791] [2730 2766 2772 2723 2712]
9 9
5
[2842 2808 2868 2811] [2888 2889 2843 2823 2888]
9 9
6
[2969 2938 2930] [2914 2962 2952 2922]
7 7
7
[2976 3004] [2994 2996]
4 4
8
[3027 3058 3053] [3041 3028 3074 3093]
7 7
9
[3184 3197 3100 3160] [3133 3166 3157 3137 3113]
9 9
10
[3296 3256 3262 3201] [3278 3275 3278 3292 3295]
9 9
11
[3327 3311] [3320 3315]
4 4
12
[3421 3366 3391 3418] [3416 3415 3415 3395 3433]
9 9
13
[3440 3470 3451] [3446 3470 3445]
6 6
14
[3520 3529] [3542 3517]
4 4
15
[3554 3582] [3582 3565]
4 4
16
[3591 3584] [3591 3595]
4 4
17
[3667 3640] [3656 3647]
4 4
18
[3695 3691] [3709 3706]
4 4
19
[3734 3715] [3737 3740 3715]
5 5
20
[3797 3770] [3799 3785]
4 4
21
[3834 3837] [3819 3810]
4 4
22
[3891 3893 3844 3933] [3843 3940 3844 3921 3860]
9 9
23
[3991 4021 4014 3990] [3962 3989 3997 3976 3975]


In [24]:
metadata_np = np.array(metadata_array)
pd.DataFrame(metadata_np).to_csv("metadata.csv", index_label=("split", "domain_remapped" "domain", "category", 'y', "path"))

['test' 'train' 'val']


In [ ]:
5% + 5% + 85%